<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test basic_SUITE:test2 result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="basic_suite.src.html#test2-1">basic_SUITE:test2/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.120.0&gt;},
     {tc_logfile,"/home/ericson/erlang_big/apps/chapter28/test/demo/ct_run.ct@ericson-Aspire-ES1-572.2019-03-23_14.49.49/test.demo.basic_SUITE.logs/run.2019-03-23_14.49.50/basic_suite.test2.html"},
     {tc_group_properties,[{suite,basic_SUITE}]},
     {tc_group_path,[]},
     {data_dir,"/home/ericson/erlang_big/apps/chapter28/test/demo/basic_SUITE_data/"},
     {priv_dir,"/home/ericson/erlang_big/apps/chapter28/test/demo/ct_run.ct@ericson-Aspire-ES1-572.2019-03-23_14.49.49/test.demo.basic_SUITE.logs/run.2019-03-23_14.49.50/log_private/"}]

=== Current directory is "/home/ericson/erlang_big/apps/chapter28/test/demo/ct_run.ct@ericson-Aspire-ES1-572.2019-03-23_14.49.49"

=== Started at 2019-03-23 14:49:50

<br />

</pre>
<div class="ct_error_notify"><pre><b>*** CT Error Notification 2019-03-23 14:49:50.241 ***</b>
basic_SUITE:test2 failed on line 14
Reason: badarith

<a href="#end">Full error description and stacktrace</a>
</pre></div>
<pre>
<a name="end"></a>


=== Ended at 2019-03-23 14:49:50
=== Location: [{basic_SUITE,test2,<a href="basic_suite.src.html#14">14</a>},
              {test_server,ts_tc,1546},
              {test_server,run_test_case_eval1,1062},
              {test_server,run_test_case_eval,994}]
=== Reason: an error occurred when evaluating an arithmetic expression
  in function  basic_SUITE:test2/1 (basic_SUITE.erl, line 14)
  in call from test_server:ts_tc/3 (test_server.erl, line 1546)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1062)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 994)
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2019 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Sat Mar 23 2019 14:49:50<!--/date--><br />
</div>
</center>
</body>
</html>
